label chap6_p3:
    mei_speaking "……咦？"
    mei "我穿好衣服走到楼下，却发现本该来的人不在。电话拨过去，也只有忙音。\n今天不是不用去学校的吗，按理来说，就是早上这个时间啊……"
    mei "想到之前的事，我有些担心彭江丽是不是又累过头。\n不会吧……要不，去她家看看吧。"

    mei "清晨的温度不高，虽然太阳早已升起，但潮湿的风还是让我忍不住打了个喷嚏。"
    mei "露水在树叶上停留，缝隙间有光线穿透，也能看到浅蓝的天空。\n如果不是急着赶路，我大概会在这停留几刻。"

    mei_speaking "嗯……"
    mei "我敲完门等了两分钟，但，好像还是没人。\n这也没办法，我总不能破门而入……我叹了口气，只好作罢。"
    mei "这回倒是不用再着急了……我苦中作乐，随意地摘取一片落下来的花瓣，放慢脚步往回走。"
    mei "天气挺好，连走路都显得没那么累了，不知道彭江丽有没有感受到……嗯？"
    mei "我被自己下意识的想法震惊了。\n为什么，会在这时想到她？"
    mei "以前似乎听过一个说法，一件事坚持七天可以养成习惯。我不知道这是谁说的，可不可靠，不过……\n我可能，的确已经习惯和彭江丽一起学习这件事了。"
    mei "就像回到小时候一样。"
    mei "如果她也那样觉得，就好了……"

    unknown_speaking "梅雨——梅雨——"
    mei_speaking "咦？"
    mei "听到有人叫自己名字，我停止遐想，转过头去看声音的主人。\n但没想到竟然是路花。"
    mei_speaking "你怎么在这？"
    lu_speaking "我的腿不是快好了嘛，就想着在外面多走点路，每天走不同的地方，没想到刚好遇到你了~你是来找小彭的吗？"
    mei_speaking "我刚去过，她不在家。"
    lu_speaking "咦？我还以为她跟你说了呢，可能没来得及。\n她们今天临时多出一节补课啦，所以没有在家哦。"
    mei_speaking "哎？真的吗？"
    lu_speaking "是这样的~毕竟是备考生嘛，她还一直那么拼命。她们的老师也很厉害，大早上的挨个打电话通知人去上课。"
    mei_speaking "这，样啊……"
    lu_speaking "别不开心哦，她肯定不是故意没告诉你的。"
    mei_speaking "我知道。"
    lu_speaking "嗯嗯，很乖哦。\n诶，对了！你想不想直接去学校找她？"
    mei_speaking "啊？可，可以吗？"
    lu_speaking "可以呀，就说是家属来接人嘛~那，我们现在走？"
    mei_speaking "好，谢谢您了。"
    lu_speaking "不用这么见外~走吧~"

    mei "之前来的时候我几乎是边晕边睡，这次坐路花的车才算真正走了一遍村里到镇上的路。"
    mei "说起来，叶成华当时为什么不借女朋友的车接我啊，至少这样我不会晕到想吐……不对，我怎么又在胡思乱想。"
    mei "开车过去大约不到一个小时，如果坐大巴，估计更久。\n这里和立涧村没有太多区别，但人更多，路更挤，外面更吵。"
    lu_speaking "走吧~前面不好停车，可能要多走一点路，抱歉啦~"
    mei_speaking "好，你……可以吗？"
    mei "我看到她拿出拐杖，有些惊讶，也不由得担心起来。"
    lu_speaking "没关系啦~这是以防万一，走吧~"
    mei "我点点头，下意识握紧包里的手机，跟在她的身后。\n说实话，我们这两人不管谁出意外，都很危险啊……总之，还是小心一点吧。"
    mei "道路虽然从泥土变成了砖石，但也是凹凸不平，走起来时咯咯作响，偶尔还会扬起飞扬的灰尘和小碎屑。"
    mei "穿过几个四五层矮楼之间的小巷，我看到标志着学校的牌子。"

    lu_speaking "到啦~好像已经放学了呢，我们直接进去吧~"
    mei_speaking "哎？可以直接进去吗？"
    lu_speaking "没问题~大家都是这样的啦，这边的管理很随便的。"
    mei "的确……学校不大，但来来往往的人很多，除了穿着校服的人，还有很多其他年龄段的跟着出入。\n好乱啊……这是我的第一反应。"
    mei "彭江丽……在哪儿？"
    lu_speaking "她们的班好像就在角落那个教室，不用爬楼梯，太好了~"
    mei_speaking "嗯……"
    mei "总感觉有很多视线扫过来，让我感觉不太舒服……我努力让自己对周围的环境置之不理，只是跟着路花的脚步。"

    lu_speaking "在哪儿呀在哪儿~小彭~"
    mei_speaking "唔……"
    mei "路花好有活力啊，感觉，好羡慕……"
    random_boy_speaking "小姐姐你是来找谁的？看起来不太眼熟啊。"
    mei_speaking "……"
    random_boy_speaking "这么漂亮，莫非是来找男朋友的？"
    mei "一个男生突然挡在面前，我皱了皱眉，不知为何，并不想回答他的话。"
    random_boy_speaking "怎么这么害羞啊，只是说两句话嘛？"
    lu_speaking "小孩，别打扰我妹妹，回自己家去吧~"
    random_boy_speaking "哇，又一个漂亮姐姐？要帮忙吗？"
    lu_speaking "没听到我说的话吗？我会打断你的腿哦~"
    random_boy_speaking "好了，知道了啦……"
    mei "好，好厉害……\n路花用力甩了甩拐杖，发出破空的刷刷声，男生只好悻悻地走了。"
    lu_speaking "嘿嘿，怎么样，厉害吧？别小看我哦~虽然腿不好使了，手臂还是很有力气的~我以前可是跳舞的呀~"
    mei_speaking "嗯，谢谢……"

    mei "教室门口人来人往，不好进去，我们干脆在附近找了个学生询问彭江丽。"
    random_girl_speaking "你们找谁？哦，我知道了。"
    random_girl_speaking "卖鱼姐——有人找你——"
    mei "……咦？"
    random_girl_speaking "喂——卖鱼的——"
    random_girl_speaking "你怎么这么慢啊？"
    peng_speaking "抱歉，刚刚在收拾东西，谢谢你叫我，是谁……"
    peng_speaking "啊。"
    mei "糟糕……\n和彭江丽对上视线的一瞬间，她的表情凝固了。"
    mei_speaking "那，那个……"
    peng_speaking "……梅雨？"
    lu_speaking "哈喽~小彭，我们边走边说吧~"
    peng_speaking "路花姐？你们……"
    mei_speaking "走，走吧。"
    peng_speaking "……嗯。"

    classmate_a_speaking "咦？你们班的卖鱼姐今天也来了啊。"
    classmate_b_speaking "就是啊，她不知道我们的老师只是客气一下的吗？"
    classmate_a_speaking "还要教村里的人，分给你们的时间不就变少了吗？"
    classmate_b_speaking "所以说嘛，真希望她家人能管管。"
    classmate_a_speaking "好好去卖鱼不就好了吗，别把鱼腥味带到教室里啊。"
    peng_speaking "……"
    mei_speaking "……"
    mei "从教室离开的时候，隐约能听到其他同学交谈的声音从背后传来。\n不……其实并不是隐约，每一句都能被听得非常清楚。"
    mei "彭江丽……她……\n我，不敢看她的表情。"

    lu_speaking "小彭，是我让她过来看看的，你别生她的气，要骂就骂我吧。"
    peng_speaking "嗯？我没有生气啦……我反而应该谢谢你们带我回去呢，这样我就不用挤大巴了。"
    mei_speaking "彭江丽……"
    peng_speaking "怎么啦？"
    mei_speaking "没……"

    mei "我们一路无言。到彭江丽的家附近后，路花把我们放下车，打完招呼就先离开了。"
    peng_speaking "你也快回去吧，马上就要吃午饭了。"
    mei_speaking "嗯……"
    mei "对不起，我果然还是想说……"
    mei_speaking "今天……学校，怎么样？"
    peng_speaking "……\n怎么问这个？挺好的啊。"
    mei_speaking "那个，因为，感觉……"
    peng_speaking "我不是都说过很好了吗？！！"
    mei_speaking "……"
    peng_speaking "……对不起，我今天可能，有点累了。\n谢谢你，今天来找我。"
    mei "不……不应该是这样的……"
    mei_speaking "那个啊，我，我努力的话，说不定，可以比他们讲得都厉害，我……"
    peng_speaking "关你什么事？！\n不要可怜我！！！"
    mei_speaking "……"
    mei_speaking "对不起。"
    peng_speaking "……"
    peng_speaking "……我，我先回去了。"
    mei_speaking "嗯。"

    mei_speaking "……"
    mei "我没有想过，我和她有一天会以这样的方式分别。"
    mei "好难受，我的心脏……"
    mei "痛死了……"
    return